name: analysis_client
version: 0.0.1
description: A client library for the dart analysis server.
authors:
  - Kendal Harland <kendaljharland@gmail.com>
dependencies:
  semver:
  meta:
dev_dependencies:
  test:
  dart_style:
